blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_published

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('list/<int:pk>/', BlogListView.as_view(), name='list'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('published/<int:pk>/', toggle_published, name='published'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import contacts, ProductListView, ProductDeleteView, ProductCreateView, ProductUpdateView, \
    ProductDetailView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('list', ProductListView.as_view(), name='list'),
    path('contacts/', contacts, name='contacts'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('view/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='view'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, verification_user, RecoveryPasswordView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('recovery_password/', RecoveryPasswordView.as_view(), name='recovery_password'),
    path('success_register/<str:register_uuid>/', verification_user, name='success_register'),
]

catalog/models.py
from django.db import models
from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название категории')
    description = models.CharField(max_length=150, verbose_name='Описание категории')

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'Категория'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Категории'  # Настройка для наименования набора объектов


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='название продукта')
    description = models.CharField(max_length=150, verbose_name='Описание продукта')
    image = models.ImageField(upload_to='product_media/', verbose_name='Превью продукта', **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(default=0, verbose_name='Цена за покупку')
    date_create = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    date_modified = models.DateField(auto_now=True, verbose_name='Дата изменения')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Автор')

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'Продукт'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Продукты'  # Настройка для наименования набора объектов


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт', related_name='version')
    number = models.FloatField(default=1.0, verbose_name='Номер версии')
    name = models.CharField(max_length=150, verbose_name='Название версии')
    is_activity = models.BooleanField(default=False, verbose_name='Актуальность')

    def __str__(self):
        return f"{self.name}, {self.product}, {self.number}"

    class Meta:
        verbose_name = 'Версия'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Версии'  # Настройка для наименования набора объектов

    def clean(self) -> None:
        super().clean()
        if Version.objects.filter(product=self.product, is_activity=True).get() != self and self.is_activity:
            raise forms.ValidationError('Активная версия может быть только одна')

catalog/forms.py
from django import forms
from catalog.models import Product, Version
from django.core.exceptions import ValidationError

danger_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('id', 'name', 'description', 'price', 'category', 'image',)

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']

        if cleaned_data in danger_words:
            raise forms.ValidationError('Название некорректное, придумайте другое.')

        return cleaned_data

    def clean_description(self):
        cleaned_description = self.cleaned_data['description']
        for exclusion_word in danger_words:
            if exclusion_word in cleaned_description.lower():
                raise forms.ValidationError('Описание содержит некорректные слова')
            return cleaned_description


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy
from django.core.cache import cache
from django.conf import settings
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Version, Category
from catalog.services import get_cached_category_list


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:list')

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        all_product = Product.objects.all()
        context_data['all_product_list'] = all_product
        context_data['category_list'] = get_cached_category_list
        return context_data

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['category_list'] = get_cached_category_list()
        return context_data


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['category_list'] = get_cached_category_list()
        version_formset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == "POST":
            context_data['formset'] = version_formset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = version_formset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if not self.request.user.is_superuser and not self.request.user.is_staff:
            self.object.owner = self.request.user
        self.object.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return super().form_invalid(form)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:list')


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/product_list.html'


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f"{name}  {phone}, {message}")
    return render(request, 'catalog/contacts.html')

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>YumYumStore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">YumYumStore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:list' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Статьи</a>
        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
        {% else %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>

<div class="container">

    {% block content %}

    {% endblock %}

</div>

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            YumYumStore
            <small class="d-block mb-3 text-muted">&copy; 2023 - {% now 'Y' %}</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Фрукты</a></li>
                <li><a class="text-muted" href="#">Овощи</a></li>
                <li><a class="text-muted" href="#">Бобы</a></li>
                <li><a class="text-muted" href="#">Рассада</a></li>
                <li><a class="text-muted" href="#">Всё, что захотите</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% load static %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <input type="submit" value="Отправить">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load media_tags %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                      <p>Хотите удалить продукт "{{ object.name }}"?</p>
                        <button type="submit" class="btn btn-primary">Подтвердить</button>
                      <a href="{% url 'catalog:list' %}" class="btn btn-warning">Отмена</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load media_tags %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Продукт
                    </h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Название</td>
                            <td>{{ object.name }}</td>
                        </tr>
                        <tr>
                            <td>Описание</td>
                            <td>{{ object.description }}</td>
                        </tr>
                        <tr>
                            <td>Категория</td>
                            <td>{{ object.category }}</td>
                        </tr>
                        <tr>
                            <td>Владелец</td>
                            <td>{{ object.owner }}</td>
                        </tr>
                        <tr>
                            <td>Версия</td>
                            <td>{% for version in object.version.all %}
                                {{ version.name }}
                                {% endfor %}</td>
                        </tr>

                    </table>

                </div>
                <div class="card-footer"></div>
            </div>
        </div>
        <div class="col-6">
            <img src="{% mediapath object.image %}"/>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load media_tags %}

{% block content %}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Продукт
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Cохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
        {% if object %}
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Версия
                    </h3>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% if not forloop.last %}
                        <hr>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
        {% endif %}
    </form>
</div>

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load media_tags %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">YumYumStore</h1>
    <p class="lead">YumYumStore - лучший онлайн магазин продуктов</p>
    <a class="btn btn-primary" href="{% url 'catalog:create' %}" role="button">Добавить новый продукт</a>
</div>

<div class="container">

    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <img src="{% mediapath object.image %}" class="card-img-top">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.price }} ₽</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li> {{ object.description|truncatewords:15 }} </li>
                        {% for version in object.version.all %}
                        <li>Активная версия: {{ version.name }}</li>
                        {% endfor %}
                        <li> Владелец: {{ object.owner }} </li>
                    </ul>
                    <a class="btn btn-lg btn-block btn-outline-primary" href="#" role="button">Купить</a>
                    {% if user.is_authenticated %}
                    <a class="btn btn-outline-danger" href="{% url 'catalog:delete' object.pk %}"
                       role="button">Удалить</a>
                    <a class="btn btn-outline-success" href="{% url 'catalog:view' object.pk %}"
                       role="button">Посмотреть</a>
                    <a class="btn btn-outline-dark" href="{% url 'catalog:update' object.pk %}"
                       role="button">Изменить</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}